i=input("Enter 10 digit number :")
y=input("")
t=input("")
r=input("")
e=input("")
w=input("")
q=input("")
a=input("")
s=input("")
f=input("")
print(i,"\n",y,t,"\n",r,e,"\n",w,q,"\n",a,s,"\n",f)
